service: iris-back

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    TODO_TABLE: IrisTodoTable
    JWT_SECRET: iris-todo-app

plugins:
  - serverless-offline

functions:
  api:
    handler: dist/main.handler
    events:
      - http:
          path: api/v1/{proxy+}
          method: any
          cors: true
resources:
  Resources:
    IrisTodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: IrisTodoTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
      DeletionPolicy: 'Retain'
      UpdateReplacePolicy: 'Retain'
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
      DeletionPolicy: 'Retain'
      UpdateReplacePolicy: 'Retain'

custom:
  serverless-offline:
    httpPort: 3000
